# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# Website Katalog Obat
# NodeJS 18.18.0
# React NextJS
# ExpressJS
# MongoDB
# Using Yarn Package Manager
# Setup complete FrontEnd, BackEnd, MongoDB

name: Node.js CI with MongoDB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.18.0]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install frontend dependencies
      run: yarn install

    - name: Build frontend
      run: yarn build

    - name: Run frontend tests
      run: yarn test

  backend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.18.0]

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --name mongodb-katalog-obat

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install backend dependencies
      run: |
        cd server
        yarn install

    - name: Start MongoDB server
      run: |
        # Restore MongoDB data from the /data/json directory
        mongorestore --db katalog_obat /data/json

    - name: Start backend server
      run: |
        cd server
        node server.js


